"""
WaterDIP engineering parser framework.

Public API for parsing infrastructure and canonical engineering models.
"""

from app.data_platform.parsing.well_logs import (
    LogFamily,
    WellLogMetadata,
    classify_curve,
)


from .base import (
    BaseParser,
    ParseSource,
    ParserContext,
    ParserOutput,
    ParserResult,
    PipelineStage,
    detect_media_type,
    normalise_extension,
    sha256_bytes,
    utc_now,
)
from .dispatcher import ParserDispatcher
from .exceptions import (
    AmbiguousParserError,
    DuplicateParserError,
    InvalidParseSourceError,
    MetadataExtractionError,
    ParserExecutionError,
    ParserNotFoundError,
    ParserRegistrationError,
    ParserSelectionError,
    ParserValidationError,
    ParsingError,
    PipelineConfigurationError,
    PipelineExecutionError,
    PipelineStageError,
    SourceReadError,
    UnsupportedFileTypeError,
)
from .models import (
    BoundingBox,
    ChunkPosition,
    ChunkType,
    ContentType,
    DataQualityStatus,
    DocumentAttachment,
    DocumentChunk,
    DocumentFigure,
    DocumentSection,
    DocumentTable,
    DocumentType,
    EngineeringEntity,
    EngineeringEntityType,
    EngineeringMetadata,
    ExtractionMethod,
    Measurement,
    ProductionContext,
    ReservoirContext,
    SourceLocation,
    SourceProvenance,
    TableCell,
    WaterDIPDocument,
    WaterDIPModel,
    WellContext,
    generate_chunk_id,
    generate_document_id,
)
from .pipeline import (
    ParsingPipeline,
    PipelineResult,
    StageExecution,
)
from .registry import (
    ParserRegistry,
    default_parser_registry,
    parser_plugin,
    register_parser,
)

from .extractors import (
    BUILTIN_PARSER_CLASSES,
    CSVParser,
    DOCXParser,
    ExcelParser,
    JSONParser,
    LASParser,
    PDFParser,
    TextParser,
    XMLParser,
    ZIPParser,
    register_builtin_parsers,
)

from .chunking import (
    BaseChunker,
    ChunkerRegistry,
    ChunkingContext,
    EngineeringChunkingPipeline,
    SectionChunker,
    TableChunker,
    TextChunker,
    WellLogChunker,
    count_tokens,
    create_default_chunker_registry,
)





__all__ = [
    "AmbiguousParserError",
    "BaseParser",
    "BoundingBox",
    "ChunkPosition",
    "ChunkType",
    "ContentType",
    "DataQualityStatus",
    "DocumentAttachment",
    "DocumentChunk",
    "DocumentFigure",
    "DocumentSection",
    "DocumentTable",
    "DocumentType",
    "DuplicateParserError",
    "EngineeringEntity",
    "EngineeringEntityType",
    "EngineeringMetadata",
    "ExtractionMethod",
    "InvalidParseSourceError",
    "Measurement",
    "MetadataExtractionError",
    "ParseSource",
    "ParserContext",
    "ParserDispatcher",
    "ParserExecutionError",
    "ParserNotFoundError",
    "ParserOutput",
    "ParserRegistrationError",
    "ParserRegistry",
    "ParserResult",
    "ParserSelectionError",
    "ParserValidationError",
    "ParsingError",
    "ParsingPipeline",
    "PipelineConfigurationError",
    "PipelineExecutionError",
    "PipelineResult",
    "PipelineStage",
    "PipelineStageError",
    "ProductionContext",
    "ReservoirContext",
    "SourceLocation",
    "SourceProvenance",
    "SourceReadError",
    "StageExecution",
    "TableCell",
    "UnsupportedFileTypeError",
    "WaterDIPDocument",
    "WaterDIPModel",
    "WellContext",
    "default_parser_registry",
    "detect_media_type",
    "generate_chunk_id",
    "generate_document_id",
    "normalise_extension",
    "parser_plugin",
    "register_parser",
    "sha256_bytes",
    "utc_now",
    "BUILTIN_PARSER_CLASSES",
    "CSVParser",
    "DOCXParser",
    "ExcelParser",
    "JSONParser",
    "PDFParser",
    "LASParser",
    "TextParser",
    "XMLParser",
    "ZIPParser",
    "register_builtin_parsers",
    "BaseChunker",
    "ChunkerRegistry",
    "ChunkingContext",
    "EngineeringChunkingPipeline",
    "SectionChunker",
    "TableChunker",
    "TextChunker",
    "WellLogChunker",
    "count_tokens",
    "create_default_chunker_registry",
]